name: lending 

data_path: "C:/Users/Vittoria/Documents/GitHub/participatory_training/data/lending/lending_club_data.csv"
result_path: "C:/Users/Vittoria/Documents/GitHub/participatory_training/results/lending/"

criteria:
  ranking_criteria:
    Demographic Parity_Worst: zero
    Equal Opportunity_Worst: zero
    Equalized Odds_Worst: zero
    Calibration_Worst: zero
    Total Profit: max
    Accuracy: max
    Unexploited Profit: min

  metrics_for_evaluation:
    - Demographic Parity_Worst
    - Equal Opportunity_Worst
    - Equalized Odds_Worst
    - Calibration_Worst
    - Total Profit
    - Accuracy
    - Unexploited Profit

  ranking_weights:
    Demographic Parity_Worst: 0.2
    Equal Opportunity_Worst: 0
    Equalized Odds_Worst: 0
    Calibration_Worst: 0.2
    Total Profit: 0.2
    Accuracy: 0.4
    Unexploited Profit: 0.0

case_specific_metrics: 
  metrics: 
    - Total Profit
    - Total Loss
    - Unexploited Profit

  case_specific_metrics_module: 
    _target_: utils.metrics.case_specific_metrics.LendingCaseMetrics

  positive_attribute_for_fairness: 'Applicant Type'
  positive_group_value: 1

reward_calculator:
  _target_: utils.rewards.get_rewards.RewardCalculator
  reward_types: ${actors.reward_types}

models:
  outcome:
    model_type: classification
    model_class: OutcomeModel
    classifier:
      _target_: sklearn.ensemble.RandomForestClassifier
    param_grid:
      n_estimators: [100, 200, 300]
      max_depth: [null, 10, 20]

  rewards:
    regressor:
      _target_: sklearn.ensemble.RandomForestRegressor
      n_estimators: 100
      max_depth: 10
      random_state: 42  
    param_grid:
      n_estimators:
        - 50
        - 100
        - 150
      max_depth:
        - null
        - 10
        - 20


actions_outcomes:
  actions_set:
    - Grant
    - Grant lower
    - Not Grant

  positive_actions_set:
    - Grant
    - Grant lower

  outcomes_set:
    - Fully Repaid
    - Partially Repaid
    - Not Repaid

  mapping:
    Fully Repaid: Grant
    Not Repaid: Not Grant
    default: Grant lower

actors: 
  actor_list: 
    - Bank 
    - Applicant
    - Regulatory
    - Oracle
    - Classifier

  reward_types: 
    - Bank 
    - Applicant
    - Regulatory

augmentation_for_rewards:
  augmentation_parameters:
    actions_set: ${actions_outcomes.actions_set}
    additional_arguments: ["Applicant Type", "Loan Amount", "Interest Rate"]


context:
  feature_columns:
    - Income
    - Credit Score
    - Loan Amount
    - Interest Rate

  columns_to_display:
    - Income
    - Credit Score
    - Loan Amount
    - Interest Rate
    - Applicant Type
    - Recoveries

  



    




    